---
# vars file for capa

service_names:
- "docker"
- "kubelet"

clusterctl_version: v1.11.1
clusterawsadm: v2.10.0

aws_region: "ap-southeast-1"
aws_access_key: ""
aws_secret_key: ""

# aws_session_token: "$AWS_SESSION_TOKEN_HERE"
cloud_formation_create: false
