$ANSIBLE_VAULT;1.1;AES256
66383665636161343665376566386436616331653437316263316661303037306636353765643337
3465343561376162356537343865323539643830626631320a636333613635633731666630623937
63393266383239646439653135643565333938666239303163396439313334386232613839303930
6539636335346634660a616633623261323262656239313732616563376365346232333161643439
38323261643065656230303533356364613962363961356563636239373361306431393162396365
64336139643630336265393261326530306639316330346436333339363537386235366536643037
34396166386333393136303633303763626433366165656237656639333131666232383433616563
65656339373037353236366366623936656132666637663262323064343036393865346637383038
6330
